# Generated by Django 5.1.5 on 2025-02-10 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_profile_address_profile_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
