# Generated by Django 5.1.5 on 2025-02-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
    ]
